import json
import sys
from pathlib import Path
from dataclasses import replace

import pytest

from voicenotes.config import AppConfig, Paths
from voicenotes.pipeline import CLEANUP_PROMPT, PROMPT_VERSION, SUMMARY_PROMPT, artifact_status, format_timestamp, process_session, retry_session, transcribe_audio


def config(tmp_path):
    return AppConfig(
        output_root=tmp_path / "VoiceNotes",
        hotkey_mods=["cmd"],
        hotkey_key="`",
        audio_device="default",
        ollama_model="qwen2.5:14b",
        auto_open=False,
    )


def paths(tmp_path):
    return Paths(tmp_path / "app", tmp_path / "run", tmp_path / "config.toml", tmp_path / "models", tmp_path / "VoiceNotes")


def test_format_timestamp_uses_hh_mm_ss():
    assert format_timestamp(3.2) == "00:00:03"
    assert format_timestamp(3661.9) == "01:01:01"


def test_transcribe_audio_runs_whisper_in_child_process(tmp_path, monkeypatch):
    audio = tmp_path / "audio.wav"
    audio.write_bytes(b"RIFF" + b"0" * 10000)
    captured = {}

    def fake_run(args, capture_output, text, check):
        captured["args"] = args
        captured["capture_output"] = capture_output
        captured["text"] = text
        captured["check"] = check

        class Result:
            stdout = json.dumps([{"start": 0.0, "end": 1.0, "text": "hello"}])

        return Result()

    monkeypatch.setattr("subprocess.run", fake_run)

    segments = transcribe_audio(audio, paths(tmp_path))

    assert segments == [{"start": 0.0, "end": 1.0, "text": "hello"}]
    assert captured == {
        "args": [sys.executable, "-m", "voicenotes.transcriber", str(audio), str(tmp_path / "models" / "whisper-large-v3-mlx")],
        "capture_output": True,
        "text": True,
        "check": True,
    }


def test_prompts_preserve_raw_language_choice():
    cleanup = CLEANUP_PROMPT.format(transcript_raw="[00:00:00 - 00:00:03] Testing, testing, one, two, three.")
    summary = SUMMARY_PROMPT.format(transcript_clean="[00:00:00 - 00:00:03] Testing, testing, one, two, three.")

    assert PROMPT_VERSION == "2026-08-28-v2"
    assert "Your default behavior is to leave text unchanged." in cleanup
    assert 'Never replace "Testing, testing, one, two, three" with "测试，测试，一，二，三"' in cleanup
    assert "When uncertain, keep the raw transcript exactly as written." in cleanup
    assert 'must not render it as "测试，测试，一，二，三"' in summary


def test_process_session_writes_all_artifacts(tmp_path, monkeypatch):
    session = tmp_path / "VoiceNotes" / "2026-08-27_143012"
    session.mkdir(parents=True)
    (session / "audio.wav").write_bytes(b"RIFF" + b"0" * 10000)

    monkeypatch.setattr("voicenotes.ollama.ensure_model_available", lambda model: None)
    monkeypatch.setattr(
        "voicenotes.pipeline.transcribe_audio",
        lambda audio, models: [
            {"start": 3.0, "end": 9.0, "text": "We discussed roadmap and 中文部分."},
        ],
    )
    responses = iter(
        [
            "[00:00:03 - 00:00:09] We discussed roadmap and 中文部分.",
            "\n".join(
                [
                    "## Meeting Metadata",
                    "Date: not specified",
                    "",
                    "## Key Discussion Points",
                    "- roadmap and 中文部分",
                    "",
                    "## Decisions Made",
                    "- not specified",
                    "",
                    "## Action Items",
                    "- [ ] follow up — owner: unassigned — deadline: no deadline given",
                    "",
                    "## Open Questions",
                    "- not specified",
                ]
            ),
        ]
    )
    monkeypatch.setattr("voicenotes.ollama.generate", lambda model, prompt, timeout_seconds=1800: next(responses))
    opened = []
    monkeypatch.setattr("subprocess.run", lambda args, check=False: opened.append(args))

    process_session(session, config(tmp_path), paths(tmp_path))

    assert (session / "transcript_raw.md").read_text(encoding="utf-8") == "[00:00:03 - 00:00:09] We discussed roadmap and 中文部分.\n"
    assert (session / "transcript_clean.md").read_text(encoding="utf-8").startswith("[00:00:03 - 00:00:09]")
    summary = (session / "summary.md").read_text(encoding="utf-8")
    assert summary.startswith("<!-- Generated by VoiceNotes from session 2026-08-27_143012 -->")
    assert "## Open Questions" in summary


def test_invalid_summary_is_saved_raw_and_fails(tmp_path, monkeypatch):
    session = tmp_path / "VoiceNotes" / "2026-08-27_143012"
    session.mkdir(parents=True)
    (session / "audio.wav").write_bytes(b"RIFF" + b"0" * 10000)
    monkeypatch.setattr("voicenotes.ollama.ensure_model_available", lambda model: None)
    monkeypatch.setattr("voicenotes.pipeline.transcribe_audio", lambda audio, models: [{"start": 0, "end": 1, "text": "hello"}])
    monkeypatch.setattr("voicenotes.ollama.generate", lambda *args, **kwargs: "Here is the summary\n\n## Meeting Metadata")

    with pytest.raises(RuntimeError, match="summary validation failed"):
        process_session(session, config(tmp_path), paths(tmp_path))

    assert (session / "summary.raw.md").exists()
    assert (session / "error.log").exists()


def test_retry_skips_valid_existing_artifacts(tmp_path, monkeypatch):
    session = tmp_path / "VoiceNotes" / "2026-08-27_143012"
    session.mkdir(parents=True)
    (session / "audio.wav").write_bytes(b"RIFF" + b"0" * 10000)
    (session / "transcript_raw.md").write_text("[00:00:00 - 00:00:01] existing raw\n", encoding="utf-8")
    (session / "transcript_clean.md").write_text("[00:00:00 - 00:00:01] existing clean\n", encoding="utf-8")
    monkeypatch.setattr("voicenotes.ollama.ensure_model_available", lambda model: None)
    monkeypatch.setattr("voicenotes.pipeline.transcribe_audio", lambda audio, models: pytest.fail("should skip transcription"))
    monkeypatch.setattr(
        "voicenotes.ollama.generate",
        lambda *args, **kwargs: "\n".join(
            [
                "## Meeting Metadata",
                "Date: not specified",
                "## Key Discussion Points",
                "- point",
                "## Decisions Made",
                "- none",
                "## Action Items",
                "- [ ] task — owner: unassigned — deadline: no deadline given",
                "## Open Questions",
                "- none",
            ]
        ),
    )

    retry_session(session, config(tmp_path), paths(tmp_path))

    assert artifact_status(session)["transcript_raw"] is True
    assert (session / "summary.md").exists()


def test_retry_regenerates_malformed_utf8_transcript(tmp_path, monkeypatch):
    session = tmp_path / "VoiceNotes" / "2026-08-27_143012"
    session.mkdir(parents=True)
    (session / "audio.wav").write_bytes(b"RIFF" + b"0" * 10000)
    (session / "transcript_raw.md").write_bytes(b"\xff\xfe")
    monkeypatch.setattr("voicenotes.ollama.ensure_model_available", lambda model: None)
    monkeypatch.setattr(
        "voicenotes.pipeline.transcribe_audio",
        lambda audio, models: [{"start": 0, "end": 1, "text": "regenerated raw"}],
    )
    responses = iter(
        [
            "[00:00:00 - 00:00:01] regenerated clean",
            "\n".join(
                [
                    "## Meeting Metadata",
                    "Date: not specified",
                    "## Key Discussion Points",
                    "- point",
                    "## Decisions Made",
                    "- none",
                    "## Action Items",
                    "- [ ] task — owner: unassigned — deadline: no deadline given",
                    "## Open Questions",
                    "- none",
                ]
            ),
        ]
    )
    monkeypatch.setattr("voicenotes.ollama.generate", lambda *args, **kwargs: next(responses))

    retry_session(session, config(tmp_path), paths(tmp_path))

    assert (session / "transcript_raw.md").read_text(encoding="utf-8") == "[00:00:00 - 00:00:01] regenerated raw\n"
    assert artifact_status(session)["summary"] is True


def test_retry_regenerates_downstream_artifacts_after_invalid_raw_transcript(tmp_path, monkeypatch):
    session = tmp_path / "VoiceNotes" / "2026-08-27_143012"
    session.mkdir(parents=True)
    (session / "audio.wav").write_bytes(b"RIFF" + b"0" * 10000)
    (session / "transcript_raw.md").write_text("", encoding="utf-8")
    (session / "transcript_clean.md").write_text("stale clean\n", encoding="utf-8")
    (session / "summary.md").write_text(
        "\n".join(
            [
                "## Meeting Metadata",
                "stale",
                "## Key Discussion Points",
                "- stale",
                "## Decisions Made",
                "- stale",
                "## Action Items",
                "- [ ] stale",
                "## Open Questions",
                "- stale",
            ]
        ),
        encoding="utf-8",
    )
    monkeypatch.setattr("voicenotes.ollama.ensure_model_available", lambda model: None)
    monkeypatch.setattr("voicenotes.pipeline.transcribe_audio", lambda audio, models: [{"start": 0, "end": 1, "text": "fresh raw"}])
    responses = iter(
        [
            "fresh clean",
            "\n".join(
                [
                    "## Meeting Metadata",
                    "fresh",
                    "## Key Discussion Points",
                    "- fresh",
                    "## Decisions Made",
                    "- fresh",
                    "## Action Items",
                    "- [ ] fresh",
                    "## Open Questions",
                    "- fresh",
                ]
            ),
        ]
    )
    monkeypatch.setattr("voicenotes.ollama.generate", lambda *args, **kwargs: next(responses))

    retry_session(session, config(tmp_path), paths(tmp_path))

    assert (session / "transcript_clean.md").read_text(encoding="utf-8") == "fresh clean\n"
    assert "- fresh" in (session / "summary.md").read_text(encoding="utf-8")


def test_process_session_rejects_empty_raw_transcript_before_cleanup(tmp_path, monkeypatch):
    session = tmp_path / "VoiceNotes" / "2026-08-27_143012"
    session.mkdir(parents=True)
    (session / "audio.wav").write_bytes(b"RIFF" + b"0" * 10000)
    monkeypatch.setattr("voicenotes.ollama.ensure_model_available", lambda model: None)
    monkeypatch.setattr("voicenotes.pipeline.transcribe_audio", lambda audio, models: [])
    monkeypatch.setattr("voicenotes.ollama.generate", lambda *args, **kwargs: pytest.fail("should not clean an invalid raw transcript"))

    with pytest.raises(RuntimeError, match="raw transcript validation failed"):
        process_session(session, config(tmp_path), paths(tmp_path))


def test_process_session_opens_valid_existing_summary_when_enabled(tmp_path, monkeypatch):
    session = tmp_path / "VoiceNotes" / "2026-08-27_143012"
    session.mkdir(parents=True)
    (session / "audio.wav").write_bytes(b"RIFF" + b"0" * 10000)
    (session / "transcript_raw.md").write_text("[00:00:00 - 00:00:01] existing raw\n", encoding="utf-8")
    (session / "transcript_clean.md").write_text("[00:00:00 - 00:00:01] existing clean\n", encoding="utf-8")
    (session / "summary.md").write_text(
        "\n".join(
            [
                "<!-- Generated by VoiceNotes from session 2026-08-27_143012 -->",
                "",
                "## Meeting Metadata",
                "not specified",
                "## Key Discussion Points",
                "- point",
                "## Decisions Made",
                "- none",
                "## Action Items",
                "- [ ] task — owner: unassigned — deadline: no deadline given",
                "## Open Questions",
                "- none",
            ]
        ),
        encoding="utf-8",
    )
    opened = []
    monkeypatch.setattr("subprocess.run", lambda args, check=False: opened.append(args))
    monkeypatch.setattr("voicenotes.pipeline.notify", lambda title, message: None)
    monkeypatch.setattr("voicenotes.ollama.ensure_model_available", lambda model: pytest.fail("should skip model preflight"))

    process_session(session, replace(config(tmp_path), auto_open=True), paths(tmp_path))

    assert opened == [["open", "-g", str(session / "summary.md")]]
