import json

from voicenotes.config import Paths
from voicenotes.state import (
    atomic_write_json,
    atomic_write_text,
    required_summary_headings,
    status_snapshot,
    validate_summary,
)


def test_atomic_write_text_replaces_file(tmp_path):
    path = tmp_path / "artifact.md"
    atomic_write_text(path, "first")
    atomic_write_text(path, "second")

    assert path.read_text(encoding="utf-8") == "second"
    assert not list(tmp_path.glob("*.tmp"))


def test_atomic_write_json_round_trips(tmp_path):
    path = tmp_path / "session.json"
    atomic_write_json(path, {"status": "ready", "count": 1})

    assert json.loads(path.read_text(encoding="utf-8")) == {"status": "ready", "count": 1}


def test_validate_summary_accepts_provenance_comment_and_exact_headings(tmp_path):
    path = tmp_path / "summary.md"
    path.write_text(
        "\n".join(
            [
                "<!-- Generated by VoiceNotes from session 2026-08-27_143012 -->",
                "",
                "## Meeting Metadata",
                "Date: not specified",
                "",
                "## Key Discussion Points",
                "- point",
                "",
                "## Decisions Made",
                "- not specified",
                "",
                "## Action Items",
                "- [ ] task — owner: unassigned — deadline: no deadline given",
                "",
                "## Open Questions",
                "- none",
            ]
        ),
        encoding="utf-8",
    )

    assert required_summary_headings() == [
        "## Meeting Metadata",
        "## Key Discussion Points",
        "## Decisions Made",
        "## Action Items",
        "## Open Questions",
    ]
    assert validate_summary(path) == (True, "ok")


def test_validate_summary_rejects_extra_top_level_section(tmp_path):
    path = tmp_path / "summary.md"
    path.write_text(
        "\n".join(
            [
                "## Intro",
                "extra",
                "## Meeting Metadata",
                "## Key Discussion Points",
                "## Decisions Made",
                "## Action Items",
                "## Open Questions",
            ]
        ),
        encoding="utf-8",
    )

    valid, reason = validate_summary(path)

    assert valid is False
    assert "unexpected heading" in reason


def test_validate_summary_rejects_additional_markdown_heading(tmp_path):
    path = tmp_path / "summary.md"
    path.write_text(
        "\n".join(
            [
                "## Meeting Metadata",
                "### Unapproved Details",
                "## Key Discussion Points",
                "## Decisions Made",
                "## Action Items",
                "## Open Questions",
            ]
        ),
        encoding="utf-8",
    )

    valid, reason = validate_summary(path)

    assert valid is False
    assert "unexpected heading" in reason


def test_status_snapshot_reports_recording_processing_queue_and_error(tmp_path):
    run = tmp_path / ".voicenotes" / "run"
    queue = run / "queue"
    queue.mkdir(parents=True)
    (run / "current-recording.json").write_text('{"session_path": "/tmp/session"}', encoding="utf-8")
    (run / "pipeline.lock").write_text('{"pid": 123}', encoding="utf-8")
    (queue / "20260827T143012_session.json").write_text('{"session_path": "/tmp/queued"}', encoding="utf-8")
    (run / "last-error.txt").write_text("failed", encoding="utf-8")

    snapshot = status_snapshot(Paths(tmp_path / ".voicenotes/app", run, run.parent / "config.toml", run.parent / "models", tmp_path / "VoiceNotes"))

    assert snapshot == {
        "recording": True,
        "processing": True,
        "queued_count": 1,
        "last_error": "failed",
        "active_session": "/tmp/session",
        "state_label": "recording",
    }
