from __future__ import annotations

from pathlib import Path
import json
import os
import tempfile

from .config import Paths


SUMMARY_HEADINGS = [
    "## Meeting Metadata",
    "## Key Discussion Points",
    "## Decisions Made",
    "## Action Items",
    "## Open Questions",
]


def atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(tmp_name, path)
    finally:
        tmp = Path(tmp_name)
        if tmp.exists():
            tmp.unlink()


def atomic_write_json(path: Path, payload: dict[str, object]) -> None:
    atomic_write_text(path, json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n")


def read_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def required_summary_headings() -> list[str]:
    return list(SUMMARY_HEADINGS)


def validate_summary(path: Path) -> tuple[bool, str]:
    if not path.exists():
        return False, "missing summary.md"
    lines = path.read_text(encoding="utf-8").splitlines()
    headings = [line.strip() for line in lines if line.startswith("## ")]
    if headings != SUMMARY_HEADINGS:
        unexpected = [heading for heading in headings if heading not in SUMMARY_HEADINGS]
        if unexpected:
            return False, f"unexpected heading: {unexpected[0]}"
        return False, "required headings missing or out of order"
    first_heading_index = next((i for i, line in enumerate(lines) if line.startswith("## ")), -1)
    prefix = "\n".join(lines[:first_heading_index]).strip()
    if prefix and (not prefix.startswith("<!-- Generated by VoiceNotes from session ") or not prefix.endswith("-->")):
        return False, "unexpected content before first heading"
    return True, "ok"


def status_snapshot(paths: Paths) -> dict[str, object]:
    recording_path = paths.run / "current-recording.json"
    lock_path = paths.run / "pipeline.lock"
    queue_path = paths.run / "queue"
    error_path = paths.run / "last-error.txt"
    active_session = None
    if recording_path.exists():
        try:
            active_session = str(read_json(recording_path).get("session_path") or "")
        except (OSError, json.JSONDecodeError):
            active_session = ""
    queued_count = len(list(queue_path.glob("*.json"))) if queue_path.exists() else 0
    last_error = error_path.read_text(encoding="utf-8").strip() if error_path.exists() else None
    recording = recording_path.exists()
    processing = lock_path.exists()
    state_label = "recording" if recording else "processing" if processing else "queued" if queued_count else "error" if last_error else "idle"
    return {
        "recording": recording,
        "processing": processing,
        "queued_count": queued_count,
        "last_error": last_error,
        "active_session": active_session,
        "state_label": state_label,
    }
